name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out the repository
      uses: actions/checkout@v2

    # Step 2: Install Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Build the project
    - name: Build the project
      run: npm run build

    # Step 5: Copy files to the server using SCP
    - name: Copy files via SCP
      run: |
        scp -r ./build/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/path/to/your/remote/directory
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 6: Restart only the serve process (or the relevant service)
      - name: Restart serve in screen session
        run: ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "screen -S microservices -X stuff 'fuser -k 8110/tcp && serve -s /path/to/your/build -l 8110\n'"
